### PR TITLE
fix #265 - rename uiClasses

### LINKED ISSUE #265: Gui Component nams don't respect the PSR
We have classes named `uiLabel` instead of `UiLabel`

This needs to be fixed.

### PR DESCRIPTION
**Pull request by reaby**

### CODE REVIEW

**Review by oliverde8 — CHANGES_REQUESTED** [review]
* Add changelog about the renames. 
* Check unit tests not passing.

**Comment by reaby** [comment]
Ok, i'll correct this.

**Comment by oliverde8** [comment]
You forgot to rename AbstractuiElement => it's still abstractuiElement. 

So on Linux it creates the error, and on travis as well. :wink:

**Comment by reaby** [comment]
Thanks

**Review by oliverde8 — APPROVED** [review]

**Pull request merged**
